# Generated by Django 5.2.11 on 2026-02-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountWithDynamicBackend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=100)),
                ("balance", models.IntegerField(default=0)),
                (
                    "backend_class",
                    models.CharField(
                        choices=[
                            ("app.backends.FirstBackend", "First Backend"),
                            ("app.backends.SecondBackend", "Second Backend"),
                        ],
                        max_length=255,
                    ),
                ),
                ("backend_config", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
